### ISSUE TITLE
Adding a new playlist

### ISSUE THREAD

**Issue by LogNog21303** [mackorone/spotify-playlist-archive#119]
hey, was wondering if you could add this playlist to your registry, there were many more songs that I found enjoyable on this playlist back in 2019 and I don't remember which ones they were.
https://open.spotify.com/playlist/37i9dQZF1DZ06evO2ZCBBm?si=b152d6d2bd904413
Thanks, man.

**Comment by mackorone** [comment]
I just added it to the archive: 2b0ed074576dfdc1d0118c64607efd38045a4321

> back in 2019

Unfortunately, I can't recover old versions of the playlist, but it'll be tracked from now on.
