### ISSUE TITLE
Manually add older songs to a spotify-playlist-archive cumulative playlist ?

### ISSUE THREAD

**Issue by joerivanleeuwen** [mackorone/spotify-playlist-archive#123]
Thanks for spotify-playlist-archive, love it.
I have a question/issue:
I know of a number of songs that were on my fav list before it got added to spotify-playlist-archive .
Is there a way to manually add songs to the cumulative list? 
 (Perhaps by e.g. just adding them by hand to the cumulative playlist file and submitting a PR?)
 Thanks, J

**Comment by mackorone** [comment]
> adding them by hand to the cumulative playlist file and submitting a PR

Yep, this should work! Note that you only need to update the `.json` file; the `.md` file will get regenerated when your changes are merged.
