### ISSUE TITLE
Proposal for generating a registry.json file

### ISSUE THREAD

**Issue by maciejpedzich** [mackorone/spotify-playlist-archive#163]
Hey Mack!

I've just noticed that you've started displaying the total number of playlist entries in the archive in `README.md`. The aforementioned search engine relies on the `## Playlists` header to remain unchanged in order to extract the list of playlist links, to then process it to extract every playlist's name and perform a fuzzy search.

Since the README no longer contains the exact `## Playlists` string, the list can't get extracted using this approach. I've implemented a short-term fix (see my comment below), where I use RegEx instead of a hardcoded string.

But in the long term, perhaps you could generate something like a `registry.json` file that would contain an array of objects with `name` and `id` fields of each playlist. That way, I wouldn't have to rely on any hacky solutions to generate a similar list myself, but instead just grab that file and perform the search pretty much immediately.

Oh, and sorry for not notifying you about that search engine implementation in the first place. This was literally the only way for me to obtain a list of all the available playlists, since GitHub's code search returned many false positives, because I couldn't use token characters like `"`, or `:` in order to look for `"title": "searchQueryHere"` substring.

**Comment by maciejpedzich** [comment]
I've just implemented [the short term fix](https://github.com/maciejpedzich/spotify-playlist-archive-website/commit/c56a42ad4c4d76bbd9cfd2d2462a941caed44708), but I'll keep the issue open for now. I'll also rename it to account for the hotfix being live as we speak.

**Comment by mackorone** [comment]
@maciejpedzich whoops, sorry about that!

https://github.com/mackorone/spotify-playlist-archive/commit/a7558ead71131c538421000644738de94d5590b6 should do the trick, but if not, let me know.

**Comment by maciejpedzich** [comment]
> @maciejpedzich whoops, sorry about that!
> 
> [a7558ea](https://github.com/mackorone/spotify-playlist-archive/commit/a7558ead71131c538421000644738de94d5590b6) should do the trick, but if not, let me know.

Awesome, I'll check it out! Thanks!

**Comment by maciejpedzich** [comment]
> @maciejpedzich just a quick FYI, you may need to wait (~1hr) for the script to run before `metadata.json` is available. Also, I chose to put _all_ of the metadata in the file, not just the playlist name, just in case you wanted to use the other fields for search, too.

Gotcha, thanks for letting me know! I've also emailed you a link to the WIP website rewrite. It's still very early in development, with only the search bar implemented right now, but feel free to check it out if you want!

**Comment by maciejpedzich** [comment]
@mackorone I've just adopted the new website's search bar component to make use of `metadata.json`. Thank you so much for the fast response earlier today, really appreciate it!
