### ISSUE TITLE
Publishing cumulative playlists back to Spotify

### ISSUE THREAD

**Issue by natejlong** [mackorone/spotify-playlist-archive#23]
Love the project, super useful! Have you ever thought of publishing the cumulative playlists back to spotify?

**Comment by mackorone** [comment]
@natejlong I'm happy you like it! No, I hadn't considered that, but I like the idea! It's unlikely that I'll get around to it, but I'm happy to review pull requests :).

**Comment by mackorone** [comment]
Thanks to @Prillan, we're now publishing cumulative playlists back to Spotify!
- GitHub repository: https://github.com/mackorone/spotify-playlist-publisher
- Published playlists: https://open.spotify.com/user/w6hfc0hfa4s53j4l44mqn2ppe/playlists

**Comment by natejlong** [comment]
:tada: This is amazing, thanks so much to the both of you!

**Comment by joerivanleeuwen** [comment]
👍 Thanks !! I'm glad to be listening to 18 hrs of all-time goodies from my favorite playlist now.
