### ISSUE TITLE
Pls add hot rhythmic playlist

### ISSUE THREAD

**Issue by joefred444** [mackorone/spotify-playlist-archive#34]

**Comment by mackorone** [comment]
Hi, I'm happy you're interested in the project. Did you already try to add it yourself? If so, what part are you stuck on?

**Comment by joefred444** [comment]
> Hi, I'm happy you're interested in the project. Did you already try to add it yourself? If so, what part are you stuck on?

I got to playlists/plain/ but don't really understand the pull request system, regardless this is a very cool project. The playlist code is 37i9dQZF1DWYs83FtTMQFw

**Comment by mackorone** [comment]
> don't really understand the pull request system

No worries, it takes some getting used to.

> The playlist code is 37i9dQZF1DWYs83FtTMQFw

Thanks for sending the playlist ID - I went ahead and added it to the archive!
