### ISSUE TITLE
"Made for me" playlist differs from scraped playlist

### ISSUE THREAD

**Issue by oavaldezi** [mackorone/spotify-playlist-archive#366]
I've noticed that a scraped playlist's content differs from what I see on Spotify. Could it be because it's a "made for me" playlist?

I'm talking about [this one](https://open.spotify.com/playlist/37i9dQZF1DWZtZ8vUCzche?si=d5b0ec3c53134d98).

**Comment by mackorone** [comment]
> Could it be because it's a "made for me" playlist?

Yes, that's exactly right. See https://artists.spotify.com/blog/our-playlist-ecosystem-is-evolving

The archive contains the content that a logged-out user would see, more or less.
