### ISSUE TITLE
Format with Black

### ISSUE THREAD

**Issue by apoclyps** [mackorone/spotify-playlist-archive#38]
### What's Required?

As outlined in https://github.com/mackorone/spotify-playlist-archive/blob/master/TODO.md, the codebase should be formatted using Black.

**Acceptance Criteria**
* Code is formatted using black
* Black is added as a dependency to the project.

**Comment by apoclyps** [comment]
Hi @mackorone, 

I think your project is awesome and It's something I would benefit from using. I've created the following issue based on a TODO outlined within your repository and created a pull request for you to review.

Please let me know if there is anything I can do to help get this pull request accepted.

**Comment by mackorone** [comment]
@apoclyps wow, this is awesome! I happy you like the project. Thanks for putting up the PR. I'll take a look soon!
