### ISSUE TITLE
Githistory with track positions

### ISSUE THREAD

**Issue by catzs** [mackorone/spotify-playlist-archive#59]
When I click on any of the options other than "pretty", it will give me an alphabetical ordering of the songs (by song name). But if I wanted to know what the order of the playlist was in a specific week in the past, I am not able to tell. Is there an easy way to enable this?

**Comment by mackorone** [comment]
> what the order of the playlist was in a specific week in the past

I think you can do this:
1. Pick a commit from the [commit log](https://github.com/mackorone/spotify-playlist-archive/commits/master)
1. Click "Browse the repository at this point in the history"
1. Navigate to the "pretty" version of the playlist you want

Does that work?

**Comment by catzs** [comment]
yes that works thank you
